# Generated by Django 4.1.7 on 2023-03-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('skills', models.TextField(max_length=50)),
                ('price', models.IntegerField()),
                ('applied', models.ManyToManyField(to='users.user')),
            ],
        ),
    ]
