# Generated by Django 4.1.7 on 2023-04-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applied',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
