# Generated by Django 4.1.7 on 2023-04-05 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_user_name'),
        ('jobs', '0004_remove_job_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applied',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
