# Generated by Django 4.1.7 on 2023-04-05 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_applied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='applied',
            new_name='posted',
        ),
    ]
