# Generated by Django 4.1.7 on 2023-04-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_user_name'),
        ('jobs', '0006_rename_applied_job_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applied',
            field=models.ManyToManyField(blank=True, related_name='jobs_applied', to='users.user'),
        ),
    ]
